"""Remove build-machine identifiers from a built wheel.

maturin records the crate as `path+file:///absolute/build/dir` in the CycloneDX
SBOM's bom-ref fields, which puts the builder's directory layout into every
released artifact. RUSTFLAGS remapping does not touch it, because the SBOM is
generated by maturin rather than by rustc.

Rewrites those refs to a stable placeholder and regenerates RECORD, since
rewriting a member invalidates its hash and size.

    sanitize_wheel.py <wheel> [--check]
"""
import base64, csv, hashlib, io, os, re, sys, zipfile

PLACEHOLDER = "path+file:///src"

def digest(data: bytes) -> str:
    return "sha256=" + base64.urlsafe_b64encode(hashlib.sha256(data).digest()).decode().rstrip("=")

def sanitize(path: str, check_only: bool = False) -> int:
    src = zipfile.ZipFile(path)
    members = [(i, src.read(i.filename)) for i in src.infolist()]
    src.close()

    changed = []
    out = []
    for info, data in members:
        if "cyclonedx" in info.filename and b"path+file://" in data:
            new = re.sub(rb'path\+file://[^"#]*', PLACEHOLDER.encode(), data)
            if new != data:
                changed.append(info.filename)
                data = new
        out.append((info, data))

    if check_only:
        return len(changed)
    if not changed:
        return 0

    # RECORD must be rebuilt: the rewritten member's hash and size changed.
    record_name = next(n for n, _ in [(i.filename, d) for i, d in out] if n.endswith(".dist-info/RECORD"))
    rows = []
    for info, data in out:
        if info.filename == record_name:
            continue
        rows.append([info.filename, digest(data), str(len(data))])
    rows.append([record_name, "", ""])
    buf = io.StringIO()
    csv.writer(buf, lineterminator="\n").writerows(rows)
    record_bytes = buf.getvalue().encode()

    tmp = path + ".tmp"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as z:
        for info, data in out:
            z.writestr(info, record_bytes if info.filename == record_name else data)
    os.replace(tmp, path)
    return len(changed)

if __name__ == "__main__":
    wheel = sys.argv[1]
    check = "--check" in sys.argv
    n = sanitize(wheel, check)
    if check:
        print(f"{n} member(s) still carry build paths")
        sys.exit(1 if n else 0)
    print(f"sanitised {n} member(s) in {os.path.basename(wheel)}")
